FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    asterisk \
    unixodbc \
    odbc-mariadb \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY config/asterisk/odbc.ini /etc/odbc.ini
CMD ["/usr/sbin/asterisk", "-fvvvv"]